kube-state-metrics:
  metricLabelsAllowlist:
    - pods=[*]
    - deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]
    - services=[*]
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
grafana:
  grafana.ini:
    plugins:
      allow_loading_unsigned_plugins: lyz-knative-datasource
  initChownData:
    enabled: false
  persistence:
    enabled: true
    storageClassName: nfs-csi
