apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  namespace: observability
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/loki
