{
 "title": "Service",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "servicenamespace",
    "label": "Function Namespace",
    "query": {
     "query": "label_values(revision_app_request_count,namespace_name)"
    }
   },
   {
    "name": "servicename",
    "label": "Function Name",
    "query": {
     "query": "label_values(revision_app_request_count{namespace_name=\"$servicenamespace\"},configuration_name)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Function Overview" } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(response_code) (rate(revision_app_request_count{service_name=\"${servicename}\", namespace_name=\"${servicenamespace}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revision Traffic",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(revision_name) (rate(revision_app_request_count{service_name=\"${servicename}\", namespace_name=\"${servicenamespace}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(revision_app_request_latencies_bucket{service_name=\"${servicename}\", namespace_name=\"${servicenamespace}\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(revision_app_request_latencies_bucket{service_name=\"${servicename}\", namespace_name=\"${servicenamespace}\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(revision_app_request_latencies_bucket{service_name=\"${servicename}\", namespace_name=\"${servicenamespace}\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cold Start",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "delta(service_start_count{service_name=\"${servicename}\", service_namespace=\"${servicenamespace}\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"$servicenamespace\", service_name=~\"$servicename-[0-9]{5}\"} | json time=\"time\", log=\"log\" | line_format `{{.log}}` | drop level, app, container, job | regexp `(?i)\\b(?P<level2>emerg|fatal|alert|crit(ical)?|eror|error|warn(ing)?|info(rmation(al)?)?|notice|dbug|debug|trace)\\b` | label_format level=level2"
    }
   ]
  },
  {
   "title": "Warning/Error/Fatal Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{namespace=\"$servicenamespace\", service_name=~\"$servicename-[0-9]{5}\"} | json time=\"time\", log=\"log\" | line_format `{{.log}}` | drop level, app, container, job | regexp `(?i)\\b(?P<level2>emerg|fatal|alert|crit(ical)?|eror|error|warn(ing)?|info(rmation(al)?)?|notice|dbug|debug|trace)\\b` | label_format level=level2 | level =~ `(?i)(emerg|fatal|alert|crit(ical)?|eror|error|warn(ing)?)`"
    }
   ]
  }
 ]
}